// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars_old = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Module Guide",
      items: [
        "module-guide/intro",
        "module-guide/reports/reports-intro",
        "module-guide/pages/pages-intro",
        "module-guide/forms/forms-intro",
        "module-guide/dashboards/dashboards-intro",
        "module-guide/component/component-intro",
        "module-guide/references/routes-json",
        "module-guide/references/api-js",
        "module-guide/references/logiks-json",
        "module-guide/dbschema/dbschema-intro",
      ],
    },
    {
      type: "category",
      label: "Logiks Reports",
      items: [
        "logiks-reports/getting-started",
        "logiks-reports/basic-example",
        "logiks-reports/core-concepts",
        "logiks-reports/props",

        {
          type: "category",
          label: "Properties",
          items: [
            "logiks-reports/properties/source",
            "logiks-reports/properties/actions-buttons",
            "logiks-reports/properties/toolbar",
            "logiks-reports/properties/datagrid",
            "logiks-reports/properties/report-slot-bindings",
            "logiks-reports/properties/rules",
            "logiks-reports/properties/cards",
            "logiks-reports/properties/kanban",
            "logiks-reports/properties/calendar",
            "logiks-reports/properties/gallery",
            "logiks-reports/properties/gantt",
            "logiks-reports/properties/gmap",
          ],
        },
        {
          type: "category",
          label: "Templates",
          items: [
            "logiks-reports/templates/grid",
            "logiks-reports/templates/cards",
            "logiks-reports/templates/kanban",
            "logiks-reports/templates/calendar",
            "logiks-reports/templates/gallery",
            "logiks-reports/templates/gantt",
            "logiks-reports/templates/gmap",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Logiks Forms",
      items: ["module-guide/references/slot-bindings"],
    },
    {
      type: "category",
      label: "Logiks InfoView",
      items: ["module-guide/references/slot-bindings"],
    },
    {
      type: "category",
      label: "Logiks Dashboard",
      items: ["module-guide/references/slot-bindings"],
    },
    {
      type: "category",
      label: "Logiks Charts",
      items: ["module-guide/references/slot-bindings"],
    },
  ],
};
export default sidebars;
