// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars_old = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Module Guide",
      items: [
        "module-guide/intro",
        "module-guide/reports/mg-reports-intro",
        "module-guide/pages/mg-pages-intro",
        "module-guide/forms/mg-forms-intro",
        "module-guide/component/mg-component-intro",
        "module-guide/dashboards/mg-dashboards-intro",
        "module-guide/charts/mg-charts-intro",
        "module-guide/dbschema/mg-dbschema-intro",
        "module-guide/references/routes-json",
        "module-guide/references/api-js",
        "module-guide/references/logiks-json",
        "module-guide/references/session-variables",
        "module-guide/references/helper-functions",
      ],
    },
    {
      type: "category",
      label: "Logiks Reports",
      items: [
        "logiks-reports/getting-started",

        {
          type: "category",
          label: "Properties",
          collapsed: false,
          items: [
            "logiks-reports/properties/reports-common-props",
            "logiks-reports/properties/source",
            "logiks-reports/properties/actions-buttons",
            "logiks-reports/properties/toolbar",
            "logiks-reports/properties/sidebar",
            "logiks-reports/properties/datagrid",
            "logiks-reports/properties/report-slot-bindings",
            "logiks-reports/properties/rules",
            "logiks-reports/properties/cards",
            "logiks-reports/properties/kanban",
            "logiks-reports/properties/calendar",
            "logiks-reports/properties/gallery",
            "logiks-reports/properties/gantt",
            "logiks-reports/properties/gmap",
          ],
        },
        {
          type: "category",
          label: "References",
          items: [
            "logiks-reports/references/formatters",
            "logiks-reports/references/sql",
            "logiks-reports/references/api",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Logiks Forms",
      items: [
        "logiks-forms/intro",
        "logiks-forms/getting-started",
        "logiks-forms/configuration",
        "logiks-forms/field-types",
        "logiks-forms/validation",
        "logiks-forms/data-sources",
        "logiks-forms/dynamic-behaviors",
        "logiks-forms/hooks-and-actions",
        "logiks-forms/persistence",
        "logiks-forms/advanced-features",
        "logiks-forms/examples",
      ],
    },
    {
      type: "category",
      label: "Logiks InfoView",
      items: ["module-guide/dashboards/mg-dashboards-intro"],
    },
    {
      type: "category",
      label: "Logiks Dashboard",
      items: ["module-guide/dashboards/mg-dashboards-intro"],
    },
    {
      type: "category",
      label: "Logiks Charts",
      items: ["module-guide/dashboards/mg-dashboards-intro"],
    },
  ],
};
export default sidebars;
