name: Logiks React Plugins Deploy Docs

on:
  push:
    branches:
      - main
    # tags:
    #   - "docs-v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy
        run: npm run deploy
        env:
          GIT_USER: OpenLogiks
          USE_SSH: false
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
